### ISSUE TITLE
Python build fails

### ISSUE THREAD

**Issue by daurnimator** [goldeneye-source/ges-code#17]
.`/build_python3.sh` fails with:

```
(cd /home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/ges_build/bin/share/man/man1; ln -s python3.4.1 python3.1)
if test "xupgrade" != "xno"  ; then \
    case upgrade in \
        upgrade) ensurepip="--upgrade" ;; \
        install|*) ensurepip="" ;; \
    esac; \
    LD_LIBRARY_PATH=/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/ges_build ./python -E -m ensurepip \
        $ensurepip --root=/ ; \
fi
Traceback (most recent call last):
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/ensurepip/__main__.py", line 4, in <module>
    ensurepip._main()
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/ensurepip/__init__.py", line 209, in _main
    default_pip=args.default_pip,
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/ensurepip/__init__.py", line 116, in bootstrap
    _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/ensurepip/__init__.py", line 40, in _run_pip
    import pip
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/__init__.py", line 9, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/log.py", line 9, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/__init__.py", line 2, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/initialise.py", line 5, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/ansitowin32.py", line 6, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/winterm.py", line 2, in <module>
  File "/tmp/tmpe7exdkc9/pip-1.5.6-py2.py3-none-any.whl/pip/_vendor/colorama/win32.py", line 7, in <module>
  File "/home/daurnimator/src/goldeneye-source/ges-code/thirdparty/python3/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: No module named '_ctypes'
Makefile:988: recipe for target 'install' failed
make: *** [install] Error 1
Deploying Python to build directories...
‘../Include/pyconfig.h’ -> ‘../ges_build/bin/include/python3.4m/pyconfig.h’
‘./bin/lib/libpython3.4m.so.1.0’ -> ‘../../../bin/mod_ges/’
cp: cannot create regular file ‘../../../bin/mod_ges/’: No such file or directory
chmod: cannot access ‘../../../bin/mod_ges/libpython*’: No such file or directory
‘../../../lib/ges/linux32/libpython3.so’ -> ‘../../../bin/mod_ges/libpython3.4m.so.1.0’

```

**Comment by droidmonkey** [comment]
There is an issue with the build process that doesn't seem to include basic modules. Looking into it now.

**Comment by 0xBADEAFFE** [comment]
Maybe you should consider to use cmake as buildsystem for ges (https://github.com/davidsansome/python-cmake-buildsystem) which makes compiling x86 python on an x64 os easier.

**Comment by droidmonkey** [comment]
Build system was transitioned to cmake.
